name: omni-found
id: omni_found
description: This is a Omnibenchmark implementation of the found paper benchmark
benchmarker: "Mark Robinson <mark.robinson@mls.uzh.ch>"

# Benchmark configuration
version: "0.1.0"

# The default software environment for this benchmark.
# One of: apptainer, conda, envmodules.
software_backend: "apptainer"

# Available software environments

software_environments:
    apptainer_env:
        name: nicely packaged environment
        description: A more verbose description, for humans reading this
        apptainer: envs/example.sif

# Stages and modules for your benchmark

stages:
  - id: DATA
    outputs:
        - id: data_ad
          path: "{dataset}_rawdata.h5ad"
    modules:
      - id: dataset_loader
        name: "loads the benchmark datasets"
        software_environment: "apptainer_env"
        repository:
          url: https://github.com/CHANGEME/data_loader
          commit: 366c5a2
        parameters:
            # A single parameter dict
            - param1: "value"
              param2: "other_value"
            # A combinatorial grid expansion
            - param1: "value"
              param2: ["1", "2", "3"]
  - id: EMB
    inputs:
        - data_ad
    outputs:
      - id: embedding_tsv
        path: "{dataset}_embedding.tsv"
    modules:
      - id: cool_method_1
        name: "the only method you will ever need"
        software_environment: "apptainer_env"
        repository:
          url: https://github.com/CHANGEME/my_method
          commit: deadbeef
        parameters:
          - param1: "value"
  - id: REG
    inputs:
        - embedding_tsv
    outputs:
      - id: cellwise_scores
        path: "{dataset}_scores.tsv"
    modules:
      - id: strict_metric_1
        name: "a very well defined metric"
        software_environment: "apptainer_env"
        repository:
          url: https://github.com/CHANGEME/the_right_metric
          commit: c0ffee
        parameters:
          - foo: "bar"
  - id: BIN
    inputs:
        - cellwise_scores
    outputs:
      - id: cellwise_binarizations
        path: "{dataset}_binarization.tsv"
    modules:
      - id: strict_metric_1
        name: "a very well defined metric"
        software_environment: "apptainer_env"
        repository:
          url: https://github.com/CHANGEME/the_right_metric
          commit: c0ffee
        parameters:

  - id: MET
    inputs:
        - data_ad
        - cellwise_scores
        - cellwise_binarizations
    outputs:
      - id: metrics_json
        path: "{dataset}_metrics.json"
    modules:
      - id: strict_metric_1
        name: "a very well defined metric"
        software_environment: "apptainer_env"
        repository:
          url: https://github.com/CHANGEME/the_right_metric
          commit: c0ffee
        parameters:
