name: omni-found
id: omni_found
description: This is a Omnibenchmark implementation of the found paper benchmark
benchmarker: "Mark Robinson <mark.robinson@mls.uzh.ch>"

# Benchmark configuration
version: "0.1.0"

# The default software environment for this benchmark.
software_backend: "conda" 
#software_backend: "apptainer" 

# Available software environments

software_environments:
  found:
    name: a conda env of found and the things it needs
    conda : envs/found-trimmed.yaml
    #conda : envs/found.yaml
#  found:
#    name: a conda env of found and the things it needs
#    apptainer: envs/found.sif

# Stages and modules for your benchmark

stages:
  - id: DATA
    outputs:
        - id: data_ad
          path: "{dataset}_raw.h5ad"
    modules:
      - id: d
        name: "loads the benchmark datasets"
        software_environment: found
        resources:
          cores: 1
        repository:
          #url: /Users/mark/projects/omb/found/found-engine
          url: https://github.com/omni-found/found-engine
          commit: 15b076a
          entrypoint: download
        parameters:
            - dataset_name: "jakel"
              subset: ["all", "Astrocytes"]

  - id: EMB
    inputs:
        - data_ad
    outputs:
      - id: embedding_tsv
        path: "{dataset}_embedding.tsv"
    modules:
      - id: embed
        name: "compute the embedding"
        software_environment: found
        repository:
          #url: /Users/mark/projects/omb/found/found-engine
          url: https://github.com/omni-found/found-engine
          commit: 15b076a
          entrypoint: embed
        parameters:
          - embed_method: "log_pca"
            dim:  30

  - id: REG
    inputs:
        - data_ad
        - embedding_tsv
    outputs:
      - id: phat_tsv
        path: "{dataset}_phat.tsv"
    modules:
      - id: regress
        name: "do the regression to get cell-level scores (phat)"
        software_environment: found
        repository:
          #url: /Users/mark/projects/omb/found/found-engine
          url: https://github.com/omni-found/found-engine
          commit: 15b076a
          entrypoint: regress
        parameters:
          - regress_method: "logit_lbfgs_nol1"

  - id: BIN
    inputs:
        - data_ad
        - embedding_tsv
        - phat_tsv
    outputs:
      - id: bin_tsv
        path: "{dataset}_binarization.tsv"
    modules:
      - id: binarize 
        name: "binarize the cell-level scores"
        software_environment: found
        repository:
          #url: /Users/mark/projects/omb/found/found-engine
          url: https://github.com/omni-found/found-engine
          commit: 15b076a
          entrypoint: binarize
        parameters:
          - binarize_method: "kmeans"

#  - id: MET
#    inputs:
#        - data_ad
#        - embedding_tsv
#        - phat_tsv
#        - bin_tsv
#    outputs:
#      - id: metrics_json
#        path: "{dataset}_metrics.json"
#    modules:
#      - id: evaluate
#        name: "evaluate performance"
#        software_environment: found
#        repository:
#          url: https://github.com/omni-found/found-engine
#          commit: main
#          entrypoint: evaluate
#        parameters:
