name: omni-found
id: omni_found
description: This is a Omnibenchmark implementation of the found paper benchmark
benchmarker: "Mark Robinson <mark.robinson@mls.uzh.ch>"

# Benchmark configuration
version: "0.1.0"

# The default software environment for this benchmark.
software_backend: "conda" # maybe conda

# Available software environments

software_environments:
    found:
        name: a conda env of found and the things it needs
        apptainer: envs/found.yaml

# Stages and modules for your benchmark

stages:
  - id: DATA
    outputs:
        - id: data_ad
          path: "{dataset}_rawdata.h5ad"
    modules:
      - id: download
        name: "loads the benchmark datasets"
        software_environment: found
        repository:
          url: https://github.com/omni-found/found-engine
          commit: main
          entrypoint: download
        parameters:
            - dataset: "jakel"

  - id: EMB
    inputs:
        - data_ad
    outputs:
      - id: embedding_tsv
        path: "{dataset}_embedding.tsv"
    modules:
      - id: embed
        name: "compute the embedding"
        software_environment: found
        repository:
          url: https://github.com/omni-found/found-engine
          commit: main
          entrypoint: embed
        parameters:
          - param1: "value"

  - id: REG
    inputs:
        - embedding_tsv
    outputs:
      - id: cellwise_scores
        path: "{dataset}_scores.tsv"
    modules:
      - id: regress
        name: "do the regression to get cell-level scores"
        software_environment: found
        repository:
          url: https://github.com/omni-found/found-engine
          commit: main
        parameters:
          - foo: "bar"

  - id: BIN
    inputs:
        - cellwise_scores
    outputs:
      - id: cellwise_binarizations
        path: "{dataset}_binarization.tsv"
    modules:
      - id: binarize 
        name: "binarize the cell-level scores"
        software_environment: found
        repository:
          url: https://github.com/omni-found/found-engine
          commit: main
        parameters:

  - id: MET
    inputs:
        - data_ad
        - cellwise_scores
        - cellwise_binarizations
    outputs:
      - id: metrics_json
        path: "{dataset}_metrics.json"
    modules:
      - id: evaluate
        name: "evaluate performance"
        software_environment: found
        repository:
          url: https://github.com/omni-found/found-engine
          commit: main
        parameters:
